# Generated by Django 5.2 on 2025-05-01 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AISecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('record_id', models.UUIDField()),
                ('analysis_type', models.CharField(max_length=50)),
                ('threat_detected', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('details', models.TextField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.UUIDField(unique=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.TextField()),
                ('previous_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('hash', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
