# Generated by Django 5.2 on 2025-05-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_block_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='record_id',
            field=models.UUIDField(),
        ),
    ]
